import { readFileSync, readdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

import { buildSchema, parse, validate } from 'graphql';
import { describe, expect, it } from 'vitest';

// Contract test: every gql document in utils/graphql/viewer must validate
// against the viewer service's schema (checked in as
// viewer-schema.snapshot.graphql, regenerated by the viewer's
// UiGraphQLContractTest, which fails whenever the snapshot goes stale).
//
// Exists because of the post-#150 outage: VoteForSequence gained a
// locationPermission argument the server never declared, GraphQL failed the
// mutation at validation, and every voting-mode show broke for ~5 days.
// Service-level unit tests mock the mutation, so only validating the real
// documents against the real schema catches this class of bug. This UI-side
// twin runs on UI-only changes, which never trigger the viewer's CI job.

const docsDir = join(dirname(fileURLToPath(import.meta.url)), '..');

// SmallRye's printed SDL references its scalars without declaring them;
// declare any missing ones so graphql-js can build the schema.
const buildSnapshotSchema = () => {
  let sdl = readFileSync(join(docsDir, 'viewer-schema.snapshot.graphql'), 'utf8');
  ['DateTime', 'Date', 'Time', 'BigDecimal', 'BigInteger'].forEach((scalar) => {
    if (!new RegExp(`scalar ${scalar}\\b`).test(sdl)) {
      sdl = `scalar ${scalar}\n${sdl}`;
    }
  });
  return buildSchema(sdl);
};

const extractDocuments = () => {
  const documents = [];
  readdirSync(docsDir)
    .filter((file) => file.endsWith('.jsx'))
    .forEach((file) => {
      const source = readFileSync(join(docsDir, file), 'utf8');
      for (const match of source.matchAll(/gql`([^`]+)`/g)) {
        // Strip Apollo MultiAPILink's client-side routing directive — the
        // server schema (correctly) doesn't know it.
        const body = match[1].replace(/@api\([^)]*\)/g, '');
        const ast = parse(body);
        const name = ast.definitions.find((d) => d.kind === 'OperationDefinition')?.name?.value ?? '<anonymous>';
        documents.push({ file, name, ast });
      }
    });
  return documents;
};

describe('viewer gql documents match the viewer service schema', () => {
  const schema = buildSnapshotSchema();
  const documents = extractDocuments();

  // Canaries: if the path or extraction regex silently breaks, fail loudly
  // instead of degrading to validating nothing.
  it('extracts the known viewer operations', () => {
    const names = documents.map((d) => d.name);
    expect(names).toContain('VoteForSequence');
    expect(names).toContain('AddSequenceToQueue');
    expect(names).toContain('GetShowForViewer');
  });

  it.each(extractDocuments().map((d) => [d.name, d.file]))('%s (%s) validates against the schema', (name, file) => {
    const doc = documents.find((d) => d.name === name && d.file === file);
    const errors = validate(schema, doc.ast);
    expect(
      errors.map(String),
      `${file} → ${name} no longer matches the viewer schema — this is the mismatch that broke voting platform-wide post-#150. ` +
        'Fix the document, or change the viewer schema first and regenerate viewer-schema.snapshot.graphql ' +
        "(./gradlew test --tests '*UiGraphQLContractTest' -DupdateViewerSchemaSnapshot=true in apps/viewer)."
    ).toEqual([]);
  });
});
